### ISSUE TITLE
Add css with restictions in single component

### ISSUE THREAD

**Issue by paarals** [Platoniq/decidim-demo#14]
Sometimes, client wants little changes in decidim platform. As a facilitation team, we use decidim for the co-creation process. Sometimes, decidim framework don't apply for the specific case. For example, sometimes filters in proposals aren't needed. 
As a facilitation team, it would be nice to add some css in the back end of decidim in order to achieve the desire behavior.

**Comment by microstudi** [comment]
this is an issue for https://github.com/Platoniq/decidim-module-decidim_awesome/

**Comment by microstudi** [comment]
Done by Awesome version 0.6.3
