### ISSUE TITLE
Refactor logo and make it compatible with chrome

### ISSUE THREAD

**Issue by verarojman** [Platoniq/decidim-demo#27]

**Comment by marta-platoniq** [comment]
https://user-images.githubusercontent.com/72607737/121676001-67d70180-cab4-11eb-96a6-a12fbe1a3c18.mov

FYI: a safari també passa com a chrome

**Comment by marta-platoniq** [comment]
Ja funciona també amb Chrome i Safari 😍 Gràcies!
