### ISSUE TITLE
Texto sobre procesos

### ISSUE THREAD

**Issue by marta-platoniq** [Platoniq/decidim-demo#3]
En bepart.platoniq.net, he intentado cambiar, a través del term customizer, el texto de ayuda que sale sobre procesos para que no confunda:
![image](https://user-images.githubusercontent.com/72607737/95989624-cc10cb00-0e2a-11eb-8ef4-a4bb9de863d3.png)

He hecho "Clear cache" (muuuchas veces), pero pasa de mi. ¿Por qué no cambia este texto? ¿Por qué tiene que aparecer siempre?
![image](https://user-images.githubusercontent.com/72607737/95989793-037f7780-0e2b-11eb-9ecd-6ebb8b6b91b6.png)

**Comment by microstudi** [comment]
estos textos creo que se pueden editar en el admin. el texto solo se usa para ponerlo por defecto. Puedes confirmar @marta-platoniq ?

**Comment by marta-platoniq** [comment]
Aaah, siii, tens raó! Merci!!
