### ISSUE TITLE
Survey Component: Bug in "show responses" and "PDF export" options

### ISSUE THREAD

**Issue by marta-platoniq** [Platoniq/decidim-demo#8]
BUG - CHAPTER 1:
I have a process with two surveys (http://bepart.platoniq.net/processes/M1): Baseline Survey and Exercise. When I click to Show Responses, I get the responses from both surveys. The same occurs when I export the results to a PDF ("select your school" and "type your answer" belong to the Exercise survey, the other questions are from the baseline survey):

![image](https://user-images.githubusercontent.com/72607737/99529889-dd587480-29a0-11eb-9298-7c5609cefdbb.png)

BUG - CHAPTER 2:
I have another process with one survey (http://bepart.platoniq.net/processes/M2): Session with Fellowship. When I click to Show Responses, I get the responses from the current survey (_(1) How have you structured the session? (2) What are the doubts that you, teachers, have about the implementation process? (3) And the students, what doubts, questions and concerns have they expressed?_) + the responses from the baseline survey. I haven't checked, but I imagine that I would have the same results when exporting to PDF: 

![image](https://user-images.githubusercontent.com/72607737/99532530-bf8d0e80-29a4-11eb-888c-10e27fe2c8a0.png)

BUG - EPILOGUE:
Both processes belong to the same process group (http://bepart.platoniq.net/processes_groups/1).

TODO:

- [ ] Add questionnaire filter to answer export & view (probably in the query)
- [ ] Add some tests in export and admin view
- [ ] Pr to decidim core/develop
- [ ] Backport 0.22, 0.23

**Comment by microstudi** [comment]
@marta-platoniq thanks @marta-platoniq

**Comment by davidbeig** [comment]
@marta-platoniq vaig amb el bug-1!

**Comment by davidbeig** [comment]
This bug has been fixed in [Fix mixing answers exports and admin management in questionnaires #6902](https://github.com/decidim/decidim/pull/6902). It has also been backported to the branches we are using in production.

I will close this issue.
